name: testing_with_route_stubs_flutter
description: A Flutter project in which I demonstrate how to stub routes in integration tests
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.2


flutter:
  uses-material-design: true




